### PR TITLE
Release process diagram

### PR DESCRIPTION
**Pull request by helenemccarron**

### CODE REVIEW

**Comment by helenemccarron** [comment]
@tomjw64 I thought the PNG might be more useful to non-technical folks so they don't have to go through the hassle of saving it and converting it.

**Comment by reedstrm** [comment]
https://rawgit.com/Connexions/Plans-and-Documents/release-diagram/diagrams/release-process/release.svg works to preview the svg directly in browser, BTW.

**Comment by reedstrm** [comment]
Actually, reading closer, I missed the  dotted-line/ OR. Just make that more obvious some how?
Or does the tester line at the top need to be _above_ the working line on the left?

**Comment by reedstrm** [comment]
Hard to talk about pictures with words. I guess I'm unclear on where Issue #333 originates - regression testing, or continuous testing. What does that isolated release above the dotted-line-or represent?

**Pull request merged**
